### ISSUE TITLE
Add example how to use WebSocket with JSON-RPC 2.0

### ISSUE THREAD

**Issue by juliandroid** [powerman/rpc-codec#16] opened 2017-03-16 16:50 UTC
I'm running jsonrpc2 with custom ReadWriteCloser becuase the underlying connection is Websocket.

s.ServeCodec(jsonrpc2.NewServerCodec(rwc, nil))

If you look at the go/src/encoding/json/stream.go:144 (refill method), the default slice size is "const minRead = 512"
So, the stream calls my Read() method by asking for exactly 512 bytes. If I have a json message with exactly that size then the Read() returns n=512 and err=nil
Then the stream calls Read() again, by asking again for new 512 bytes. Since there is no data to return, the method returns n=0, and err=io.EOF which is what is expected by the Reader interface.

Unfortunately that produces "empty" string/json, so that propagates back to ReadRequestHeader method  ( go/src/github.com/powerman/rpc-codec/jsonrpc2/server.go ),which cause errParse and shutdown of the RPC handler/current websocket connection.

The only workaround in my Read() is to return the second time n=0, err=nil which is "discouraged" according to the documentation.

**Comment by juliandroid** [comment] 2017-03-16 21:14
Since I cannot replicate the problem when I use jsonrpc2 (TCP server) with custom ReadWriteCloser (based on strings.NewReader) or by sending directly prepared json via TCP client, don't spend time on this unless I manage to create an example in playground that reproduces my issue.

**Comment by juliandroid** [comment] 2017-03-17 16:42
https://play.golang.org/p/lmHyvLxFrm

I've managed to figure out the issue.
By convention io.Reader is non-blocking, or at least is not mandatory to be blocking:
golang.org/pkg/io/#Reader: "Read conventionally returns what is available instead of waiting for more"

Unfortunately that is not how it works in practice. The RPC and JSON obviously expect to work with already received in full requests which might be true or not depending of the connection/protocol type.

Basically if you have a non-blocking stream of data you'll always get a {"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}
Although two sequential Read() calls returns n=512, err=nil and then n=0, err=EOF  that is NOT enough to prevent RPC/JSON to fail with Parse error.

If you uncomment lines from 35-37 (see the source above) you'll see that everything start to work correctly, because this practically makes the reading blocking (the JSON decoder will call Read() over and over again.

In my case that is particularly weird because if you have a json rpc request that is exactly 512 bytes (which happen to be the initial buffer size) will cause double calls to Read() method: first time returning 512 bytes and err=nil and second call with 0 bytes and err=io.EOF - that make the RPC call to fail. Because the second Read() returns n=0 and err=EOF.

This issue prevents proper stacking of RPC JSON and Websocket(Gorilla).

Currently there are two workarounds if you have to implement custom ReadWriteCloser that works with Websocket:
1. If you happen to read n=0 and have err=io.EOF, return err=nil instead, which will cause the RPC to call again your Read() method where you have to call NextReader(), which is blocking.
2. Read always the requested bytes, but return one less (n-1). Store that last byte and return it with the next call of Read(). That ensures that you never return n=0 with err=EOF.

**Comment by powerman** [comment] 2017-03-18 17:31
Well, I believe this issue is about something else. At least - issue in your code example, not sure about original issue.

First, it has nothing with 512 bytes - changing your `json` var to different size makes no difference.
Second, actual result isn't just a "Parse error", there are actually two results: correct result from method call AND parse error - and this is intended behaviour! These two results has different `id` values, so it's ease to distinguish which one is related to original request.

Here is simplified example:

```go
package main

import (
	"io"
	"io/ioutil"
	"log"
	"net/rpc"
	"os"
	"strings"
	"time"

	"github.com/powerman/rpc-codec/jsonrpc2"
)

type ExampleSvc struct{}

func (*ExampleSvc) MapLen(m map[string]string, res *int) error {
	*res = len(m)
	return nil
}

const json = `{"jsonrpc":"2.0","id":0,"method":"ExampleSvc.MapLen","params":{"a":"10","b":"20"}}`

type Reader struct {
	r io.Reader
}

func (r *Reader) Read(p []byte) (n int, err error) {
	n, err = r.r.Read(p)
	log.Println("Read:", n, err)
	return
}

func main() {
	s := rpc.NewServer()
	s.Register(&ExampleSvc{})

	s.ServeCodec(jsonrpc2.NewServerCodec(struct {
		io.Reader
		io.Writer
		io.Closer
	}{
		Reader: &Reader{strings.NewReader(json)},
		Writer: os.Stdout,
		Closer: ioutil.NopCloser(nil),
	}, nil))
	time.Sleep(time.Second)
}
```
Output:
```
2017/03/18 19:23:50 Read: 82 <nil>
2017/03/18 19:23:50 Read: 0 EOF
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}
{"jsonrpc":"2.0","id":0,"result":2}
```

The "Parse error" happens on EOF because "nothing" isn't a correct JSON RPC 2.0 request. Usually clients doesn't use half-closed connections, so if server receives EOF from client then client has already closed this connection, so sending "Parse error" is safe and has no effect.

The "Parse error" result comes first because processing real RPC takes some time, while reading next request (EOF) and replying to it (Parse error) happens asynchronously to real RPC and much faster than real RPC.

**Comment by powerman** [comment] 2017-03-18 17:52
I suppose correct solution to your issue with websocket is to use special knowledge about "single websocket message always contains exactly one JSON RPC 2.0 request" and then use `ServeRequest()` instead of `ServeConn()` to handle requests one-by-one. Consider these changes to my example:

```go
func main() {
	s := rpc.NewServer()
	s.Register(&ExampleSvc{})

	var res bytes.Buffer
	s.ServeRequest(jsonrpc2.NewServerCodec(struct {
		io.Reader
		io.Writer
		io.Closer
	}{
		Reader: strings.NewReader(json),
		Writer: &res,
		Closer: ioutil.NopCloser(nil),
	}, nil))
	log.Print(res.String())
}
```
Output:
```
2017/03/18 19:49:51 {"jsonrpc":"2.0","id":0,"result":2}
```

**Comment by juliandroid** [comment] 2017-03-18 21:16
Thanks for looking into it.

Yes, I've noticed that there were two results - one successful and one with ParseError, unfortunately the first, successful response never went through due to the ParseError and the main problem was that the Websocket is immediately closed.

The problem with Websocket and that exact buffer size of 512 is that the NextReader() returns always a "Reader" that has the entire JSON message, so it is always safe to read from it till the EOF. However, if your message is exactly 512 bytes that means calling the Read() method of the returned Reader will cause "non-blocking"-like behavior i.e. it will return n=512 and err=nil, followed by second call n=0 and err=io.EOF. Unfortunately that doesn't work (with ServeConn) because second message (parsing null-size string as JSON) fails the entire request. Consequently that closes the Websocket connection.
If the message is less than 512 or bigger than 512 (i.e. still fragmented, but never returning for the second Read() call n=0 with err=EOF) you never see that problem.

Thanks for the suggestion: I'll take a look at your proposal for using ServeRequest(). And I'll test my edge case too.

Thanks again.

**Comment by juliandroid** [comment] 2017-03-19 19:09
I've created a simplified jsonrpc+websocket to check how it will behave with ServeRequest, also with ServeCodec.

```go
package main

import (
	"log"
	"net/http"
	"net/rpc"

	"time"

	"io"

	"strings"

	"github.com/gorilla/websocket"
	"github.com/powerman/rpc-codec/jsonrpc2"
)

var url = "localhost:7443"

var upgrader = websocket.Upgrader{
	ReadBufferSize:  4096,
	WriteBufferSize: 4096,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func StartServer() {
	// http://www.websocket.org/echo.html
	// ws://localhost:7443/wsr	// for ServeRequest
	// ws://localhost:7443/wsc	// for ServeCodec
	// JSON: {"jsonrpc":"2.0","method":"HelloService.Hello","params":{"msg":"The quick brown fox jumps over the lazy dog"},"id":0}
	http.HandleFunc("/wsr", wsServe)
	http.HandleFunc("/wsc", wsServe)
	http.ListenAndServe(url, nil)
}

func wsServe(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)

	if err != nil {
		log.Println(err)
		return
	}
	defer conn.Close()

	if strings.Contains(r.RequestURI, "/wsr") {
		wsHandleRequest(conn)
	} else if strings.Contains(r.RequestURI, "/wsc") {
		wsHandleCodec(conn)
	}

}

func wsHandleCodec(ws *websocket.Conn) {
	defer func() {
		deadline := time.Second
		wsClose(ws, deadline)
		ws.Close()
	}()

	rwc := &WebsocketServerConn{Ws: ws}
	s := rpc.NewServer()
	comm := &HelloService{}
	s.Register(comm)

	codec := jsonrpc2.NewServerCodec(rwc, nil)
	log.Printf("ServeCodec...\n")
	s.ServeCodec(codec)

	log.Printf("Exiting wsHandleCodec!!!\n")
}

func wsHandleRequest(ws *websocket.Conn) {
	defer func() {
		deadline := time.Second
		wsClose(ws, deadline)
		ws.Close()
	}()

	rwc := &WebsocketServerConn{Ws: ws}
	s := rpc.NewServer()
	comm := &HelloService{}
	s.Register(comm)

	for {
		codec := jsonrpc2.NewServerCodec(rwc, nil)
		log.Printf("ServeRequest...\n")
		err := s.ServeRequest(codec)

		if err != nil {
			log.Printf("Codec error: %v\n", err)
			if err != io.EOF {
				break
			}
		}
	}
	log.Printf("Exiting wsHandleRequest!!!\n")
}

func wsClose(ws *websocket.Conn, deadline time.Duration) error {
	return ws.WriteControl(websocket.CloseMessage, []byte{}, time.Now().Add(deadline))
}

type HelloService struct{}

type HelloServiceArgs struct {
	Msg string
}

type HelloServiceReply struct {
	Data string `json:"string"`
}

func (s *HelloService) Hello(args *HelloServiceArgs, reply *HelloServiceReply) error {
	log.Printf("Execute method: HelloService.HelloServiceArgs()\n")
	(*reply).Data = "Echo: " + args.Msg

	return nil
}

type WebsocketServerConn struct {
	Ws *websocket.Conn
	r  io.Reader
	w  io.WriteCloser
}

func (wc *WebsocketServerConn) Read(p []byte) (n int, err error) {
	if wc.r == nil {
		_, wc.r, err = wc.Ws.NextReader()

		if err != nil {
			return 0, err
		}
	}

	n, err = wc.r.Read(p)

	log.Printf("n=%v, err=%v\n", n, err)

	//if n == 0 && err == io.EOF {
	//	wc.r = nil
	//	err = nil
	//}

	if err == io.EOF {
		wc.r = nil
	}

	return
}

func (wc *WebsocketServerConn) Write(p []byte) (n int, err error) {
	if wc.w == nil {
		wc.w, err = wc.Ws.NextWriter(websocket.TextMessage)
		if err != nil {
			return 0, err
		}
	}

	n, err = wc.w.Write(p)

	if err != nil || n == len(p) {
		err = wc.Close()
	}

	return

}

func (wc *WebsocketServerConn) Close() (err error) {
	if wc.w != nil {
		err = wc.w.Close()
		wc.w = nil
	}

	return
}

func main() {
	log.Printf("Starting http server at %v\n", url)
	StartServer()
}
```

I hope I didn't mess up something with the example.

For this example, I'm using public echo service: http://www.websocket.org/echo.html

Running the example with URL:  ws://localhost:7443/wsr  (for ServeRequest) and ws://localhost:7443/wsc  (for ServeCodec) still produce ParseError message, which BTW I fail to understand why that is intended and is not bug in the RPC?

As you said no one expects that if you return n=0, err=EOF , this to produce valid JSON and thus I see no reason why RPC code should even try to evaluate (and optionally kill the connection when used ServeCodec). In case of ServeRequest, that doesn't close the connection, but still returns ParseError response (which browser client have to ignore).

If I uncomment lines 141 to 143 (that effectively causes Read() to call next time the NextReader() instead to continue to read via Read(), which blocks until next json comes), that avoids all ParseError issues, but just because the "stream" became blocking. I.e. always send err=nil for the case when you have n=0,err=EOF.

Any suggestions? Do you think that bug should be reported somewhere else?

**Comment by powerman** [comment] 2017-03-19 23:22
I don't have time to check you code, maybe I'll check it tomorrow or day after tomorrow.

In general, I tend to agree with you: it doesn't makes much sense to send ParseError as response to nothing. But I've re-read both specs and I'm not sure such behaviour conforms to the specs, it's actually more like it violate both specs.

So, I've created branch `no-parseerror-on-eof` with this change to let you test it for now, and send question to maillist about this issue https://groups.google.com/forum/#!topic/json-rpc/7uZkihEad14 - that's all I can do for you now. I don't like to merge into master change which may violate the spec, because there is high chance I'll have to revert this change later and thus break a lot of user apps.

**Comment by juliandroid** [comment] 2017-03-20 11:18
Looking at the encoding/json/stream.go: peek() and refill() methods it seems that this problem is predetermined and I don't think the current behavior is intended.

refill() uses minimum-size buffer, so it doesn't read the entire message, but only up to the buffer length.
peek() takes whatever refill() supplied and the only way to avoid returning an error is for the refill() to return at least one byte (i.e. line stream.go:494 return c, nil). If the refill() return n=0 with err=EOF that skips the inner for{} and peek() will propagate the error. If the refill() return n, where n>0 with err=EOF, that EOF error is lost (it is replaced with nil).

As a result the parser will return the parsed json, but next time code invoke refill() it will return n=0,err=EOF which will produce the second empty request and ParseError response.

The important thing here is that you never sent an empty request, it is just the json/stream made it look that way.

And to be entirely correct, this problem happens, only if you have a reader that doesn't know how much is size of the request. If you have a custom ReadWriteCloser and underlying connection can only be read and you cannot find the length in advance (which is also restricted by the fact that you are not supposed to return the entire message, but only as much as the refill() asked you to return).
Not having the length means that you are always end up with passing one trailing n=0,err=EOF.

This problem can be fixed inside my custom Reader, but requires a special knowledge about how json/stream and rpc work internally. Not having to worry about that is the ideal solution. The minimum is at least documenting that behavior.

**Comment by powerman** [comment] 2017-03-21 00:49
> Running the example with URL: ws://localhost:7443/wsr (for ServeRequest) and ws://localhost:7443/wsc (for ServeCodec) still produce ParseError message

Actually, it works for ws://localhost:7443/wsr, here is log of successful request:
```
2017/03/21 02:41:53 ServeRequest...
2017/03/21 02:41:53 n=117, err=<nil>
2017/03/21 02:41:53 Execute method: HelloService.HelloServiceArgs()
2017/03/21 02:41:53 ServeRequest...
2017/03/21 02:41:53 n=0, err=EOF
2017/03/21 02:41:53 Codec error: EOF
2017/03/21 02:41:53 ServeRequest...
2017/03/21 02:41:53 Codec error: rpc: server cannot decode request: websocket: close 1005 (no status)
2017/03/21 02:41:53 Exiting wsHandleRequest!!!
```

I failed to make http://www.websocket.org/echo.html works both with unsecure ws:// protocol and with localhost - probably I've too many protection plugins in Firefox (NoScript, uMatrix, HTTPS Everywhere, …) and they block insecure access and access from websites to local network.

So, I've saved example webpage from http://www.websocket.org/echo.html into file, modified these lines:
```js
var wsUri = "ws://localhost:7443/wsr";
  doSend('{"jsonrpc":"2.0","method":"HelloService.Hello","params":{"msg":"The quick brown fox jumps over the lazy dog"},"id":0}');
```
then opened this file in Firefox from harddrive and got successful result:
```
WebSocket Test

CONNECTED

SENT: {"jsonrpc":"2.0","method":"HelloService.Hello","params":{"msg":"The quick brown fox jumps over the lazy dog"},"id":0}

RESPONSE: {"jsonrpc":"2.0","id":0,"result":{"string":"Echo: The quick brown fox jumps over the lazy dog"}}

DISCONNECTED
```
To be honest, I didn't checked your code yet, but… it works with ServeRequest, as expected, and ServeRequest is recommended way to handle such cases, so… is there still any issue here?

**Comment by powerman** [comment] 2017-03-21 01:48
> Looking at the encoding/json/stream.go: peek() and refill() methods it seems that this problem is predetermined and I don't think the current behavior is intended.

I don't see any issues with everything you've described in this message. It works exactly as it should works and there is nothing to fix.

Anyway, here is simplified version of your example which use everything ServeRequest in correct way, as it was intended to be used from higher level protocols which deliver "messages" instead of "byte stream". It doesn't have "try to process fake empty request on EOF and return useless ParseError" issue.

```go
package main

import (
	"bytes"
	"io/ioutil"
	"log"
	"net/http"
	"net/rpc"

	"time"

	"io"

	"github.com/gorilla/websocket"
	"github.com/powerman/rpc-codec/jsonrpc2"
)

var url = "localhost:7443"

var upgrader = websocket.Upgrader{
	ReadBufferSize:  4096,
	WriteBufferSize: 4096,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func StartServer() {
	// http://www.websocket.org/echo.html
	// ws://localhost:7443/
	// JSON: {"jsonrpc":"2.0","method":"HelloService.Hello","params":{"msg":"The quick brown fox jumps over the lazy dog"},"id":0}
	rpc.Register(&HelloService{})
	http.HandleFunc("/", wsServe)
	http.ListenAndServe(url, nil)
}

func wsServe(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}
	defer conn.Close()

	wsHandleRequest(conn)
	wsClose(conn)
	log.Println("Exiting wsServe")
}

func wsHandleRequest(ws *websocket.Conn) {
	for {
		_, req, err := ws.ReadMessage()
		if err != nil {
			log.Println("ReadMessage:", err)
			return
		}
		var res bytes.Buffer

		log.Println("ServeRequest...")
		err = rpc.ServeRequest(jsonrpc2.NewServerCodec(struct {
			io.ReadCloser
			io.Writer
		}{
			ioutil.NopCloser(bytes.NewReader(req)),
			&res,
		}, nil))
		if err != nil {
			log.Println("ServeRequest:", err)
			return
		}

		ws.WriteMessage(websocket.TextMessage, res.Bytes())
		if err != nil {
			log.Println("WriteMessage:", err)
			return
		}
	}
}

func wsClose(ws *websocket.Conn) error {
	const deadline = time.Second
	return ws.WriteControl(websocket.CloseMessage, []byte{}, time.Now().Add(deadline))
}

type HelloService struct{}

type HelloArgs struct {
	Msg string
}

type HelloResult struct {
	Data string `json:"string"`
}

func (s *HelloService) Hello(args *HelloArgs, reply *HelloResult) error {
	log.Println("Execute method: HelloService.Hello()")
	reply.Data = "Echo: " + args.Msg
	return nil
}

func main() {
	log.Println("Starting http server at", url)
	StartServer()
}
```

**Comment by juliandroid** [comment] 2017-03-21 13:24
Thanks for those suggestions. In your opinion, things boil down to the conclusion that ServeCodec is wrong method for use with Websocket protocol.

As I said earlier, that will be great to be documented. Probably (your example) would be great to be added as reference, since its hard to find correct example :)

**Comment by powerman** [comment] 2017-04-03 00:08
> In your opinion, things boil down to the conclusion that ServeCodec is wrong method for use with Websocket protocol.

Well, that's not exactly correct. My opinion - you should use ServeCodec just like remote RPC service. I.e. if your Websocket server part works like intermediate proxy which tunnels requests from many Websocket clients to single JSON RPC 2.0 server, then it should works in this way:
- when Websocket client connects to Websocket server that Websocket server should **open new connection** to ServeCodec **and keep it open** until this Websocket client disconnects
- each Websocket message received from Websocket client should be sent to ServeCodec
- bytes read from ServeCodec should be accumulated until full JSON object will be read, then bytes of that JSON object should be sent as single Websocket message to Websocket client
- when Websocket client disconnects from Websocket server then related connection to ServeCodec should be closed

But this way you'll have to implement more complicated ReadWriter. Probably with ServeCodec and such complicated ReadWriter it'll work more effective than with ServeRequest (at least you won't have to create one-shot ServerCodec objects on each request). But ServeRequest way is easier to implement and probably should be used until you'll really have to optimize this place.

**Comment by fpawel** [comment] 2018-06-04 06:07
Good day! The example with `ServeRequest` is very usefull? thank you.
I am trying to make [rpc client over websocket](https://stackoverflow.com/questions/50669173/how-to-set-up-a-gorilla-websocket-connection-to-acts-as-json-rpc-client-for-brow). Do you think I should use the method described above? Or is it preferable to implement `ServeCodec ` proposed by [ThunderCat](https://stackoverflow.com/users/5728991/thundercat)?

**Comment by powerman** [comment] 2018-06-04 10:15
You developing a **client**? I.e. your browser application connects to backend using websocket, and then backend works as a **RPC client** and send RPC requests to browser application? Usually browser application is a client and both connects to backend and send RPC requests to backend.

I think implementing ClientCodec is a bit overkill. Probably simpler solution is to use [NewClient](https://godoc.org/github.com/powerman/rpc-codec/jsonrpc2#NewClient) and provide it with io.ReadWriteCloser implementation which convert read/writes to websocket operations. If your browser application expect whole RPC request in single websocket message then you may need to buffer writes until get whole JSON message and then send single websocket message.

**Comment by fpawel** [comment] 2018-06-04 13:10
Yes, I develop the server part of the application in Go, and the client part in Typescript. Json-rpc is used as a protocol by which a client side receives notifications from server.

Thanks for your appreciation of expediency for `ClientCodec`, this is important. At the moment, the level of complexity of implementation `ClientCodec ` is acceptable for me. Perhaps in the future I will return to this issue and consider the possibility of writing an implementation `io.ReadWriteCloser` for a cleaner code. Now I have no idea how to determine inside of `Write(p []byte) (n int, err error)`, that could give `io.Writer` implementation - is there a whole json request in argument `p` or not.

**Comment by fpawel** [comment] 2018-06-04 15:31
It seams right. Not sure about `func (x *client) Read(p []byte) (int, error){`. What if `len(b) > len(p)` - raise error like this, panic or ignore?
```
package jsonrpc2ws

import (
	"github.com/powerman/rpc-codec/jsonrpc2"
	"github.com/gorilla/websocket"
	"bytes"
	"encoding/json"
	"errors"
)

func NewClient(ws *websocket.Conn) *jsonrpc2.Client {
	c := &client{
		ws:ws,
		b:bytes.NewBuffer(nil),
	}
	return jsonrpc2.NewClient(c)
}

type client struct {
	ws *websocket.Conn
	b *bytes.Buffer
}

func (x *client) Write(p []byte) (n int, err error){
	n,err = x.b.Write(p)
	if err != nil {
		panic(err)
	}
	var b json.RawMessage
	if json.Unmarshal(x.b.Bytes(), &b) == nil {
		err = x.ws.WriteMessage(websocket.TextMessage, b)
		x.b.Reset()
	}
	return
}

func (x *client) Read(p []byte) (int, error){
	_,b,err := x.ws.ReadMessage()
	if err != nil {
		return len(b), err
	}
	if len(b) > len(p) {
		return len(b), errors.New("not enough buffer")
	}	
	return copy(p,b), err
}

func (x *client) Close() error{
	return nil
}
```

**Comment by fpawel** [comment] 2018-06-04 18:53
Many thanks for the help and demonstration of the excellent techniques of Golang. 
I corrected the code according to your recommendations https://play.golang.org/p/B0CRAgZzijo

**Comment by juliandroid** [comment] 2018-06-05 21:58
I've noticed a problem with your code sample.
```func (x client) error() (err error) ```

The receiver should be writable otherwise your locking won't work, because every time you call 
```x.mu.Lock()``` and ```x.mu.Unlock()``` will be run on a new copy (so you are creating a new mutex every time you call error().

**Comment by fpawel** [comment] 2018-06-06 17:58
Thank you, @juliandroid. It was inattention on my part.

**Closed** 2020-09-27 20:45 UTC
