### ISSUE TITLE
Memory leaks: no data in channel

### ISSUE THREAD

**Issue by Scukerman** [powerman/rpc-codec#23] opened 2018-02-20 11:56 UTC
Line 117 makes connection goroutine stuck.
https://github.com/powerman/rpc-codec/blob/f48fde47c18678cf6598875e97042ab0ec205790/jsonrpc2/http.go#L107-L121

So after a couple of hours we have 2Gb of memory allocated. And it keeps growing.

I don't know how to fix it (don't even know where the real bug is) but we made a workaround:
```golang
func (conn *httpClientConn) Read(buf []byte) (int, error) { 
	if conn.body == nil { 
		select {
		case conn.body = <-conn.ready:
		case <-time.After(time.Second * 30):
			return 0, io.EOF
		}
	}

...

}
```

Not a smart one but at least it stopped growing as fast as hell.

**Comment by powerman** [comment] 2018-02-20 19:07
It looks like you're creating a lot of Client objects with NewHTTPClient() or NewCustomHTTPClient(). It isn't supposed to be used in this way, you should create just one object (per endpoint url of service you're calling to, which usually means one object per remote service), and use that object to send any amount of RPC requests to that service/endpoint.

But you may be right about possible bug in this place - if you manage to put Client in a state when you're waiting for server's reply, and this reply won't be received, then it looks like you won't be able to interrupt this Read() method by just calling client.Close().

I've an idea how to fix client.Close() to correctly cleanup things (interrupt Read() and finish related goroutine), but to test it I need code example which creates this state (block forever in Read()) - and at the moment I've no idea how you manage to get into this state. So, if you'll provide a code example which demonstrate the issue - I should be able to fix it. (Meanwhile you should be able to fix it yourself by just using one or few Client objects instead of creating and destroying a lot of them - this is anyway right and recommended way to use objects like http.Client or rpc.Client.)

**Comment by Scukerman** [comment] 2018-02-20 21:41
Yeah, you're right. I have checked this microservice where the library is used in and found out that the service's developer just uses it this kinda way. He creates a client on each request.
I asked him why he has done it and he told me that he had run into the different issue when transport started to stop working after the first invocation (as I remember right, it's related to unstable server and bad responses). That's why he managed to make a workaround this way.

Of course, you were not expecting to use it in this way but still it may have a chance to work correctly.

**Comment by powerman** [comment] 2018-02-21 05:51
BTW, unstable server and bad responses shouldn't break Client in most cases… probably only case when it may be affected is server which begin sending response and hangs before whole response was sent, but this is quite unusual situation for JSON-RPC as it is packet-oriented, so whole response is usually available on server before it'll start sending response, so chance to hang in the middle of sending is very low.

If you can't provide code example which demonstrate the issue then you can try this fix instead of your timeout workaround (untested, will panic if Close() is called twice):
```go
func (conn *httpClientConn) Read(buf []byte) (int, error) {
	if conn.body == nil {
		conn.body, ok = <-conn.ready
		if !ok {
			return 0, io.EOF
		}
	}
	…
}

// Close must not be called more than once.
func (conn *httpClientConn) Close() error {
	close(conn.ready)
	return nil
}
```

**Comment by powerman** [comment] 2018-02-21 06:02
Huh. As usually with untested code - it doesn't work. I've pushed working (at least - it pass existing tests) fix to branch `23-fix-leak-on-close` in commit 7e75941, and it's a bit more complicated.

**Comment by Scukerman** [comment] 2018-02-21 08:32
Anyway, I don't know why it might cause this problem but he decided to do it this way (it's safer to use it like this in a very concurrent code).
So the second problem is in errors. If smth goes wrong and any error is detected, then no call will be invoked after.

Check input function in `net/rpc`:
https://golang.org/src/net/rpc/client.go

Line 151 and then Line 77.
If any error happens, then `client.shutdown` is set and client stops working.

To make 100 RPS he decided to make the workaround.

Thx for the fix, we'll gonna try it.

**Comment by powerman** [comment] 2018-02-21 09:18
100 RPS isn't really high rate, so creating new Client per request may work good enough, but with higher request rate this (creating/destroying Client per request) will became an issue on it's own.

While TCP Client may and will stop working if/when underlying connection will be closed (by server), HTTP Client should never stop working. Only issue which may happens with HTTP Client - it may hang in that Read() method in case server neither send response body nor close connection. Only way to work around this on client side is to set read timeout (plus, maybe, use pool of 8-16 Client objects for sending requests to minimize chance to delay all requests because of read timeout on some request).

To add read timeout all you need is to use something like `jsonrpc2.NewCustomHTTPClient(url, &http.Client{Timeout:15*time.Second})` instead of `jsonrpc2.NewHTTPClient(url)`.

**Comment by antness** [comment] 2018-02-21 12:23
Here's code to reproduce issue with ErrShutdown:
https://gist.github.com/antness/aab5fe6771235cd15f3b494868365fe7

We have no control over server side handler, so our client needs ability to survive any kind of invalid response.

**Comment by powerman** [comment] 2018-02-21 13:23
I see. This is JSON-RPC 2.0 protocol level error, while I was thinking about HTTP transport level error. 

Transport level errors (like wrong HTTP headers or incomplete JSON response received) are supposed to be temporary, so Client handle them as non-fatal errors and continue to work.
Protocol level errors usually mean this server isn't compatible with JSON-RPC 2.0, which is fatal error and there is no sense in continue sending requests to this server - so Client shutdown in this case.

If you really have actual service which *sometimes* reply to correct JSON-RPC 2.0 requests with incorrect JSON-RPC 2.0 responses, then this package probably should implement an optional feature to turn protocol level errors to non-fatal ones. If this is just a theoretical "possible issue", then probably you should just ignore it - there are unlimited amount of things which may go wrong, and we just can't protect our code against really-really all of them.

But, honestly, it's hard for me to believe someone has developed and deployed to production service, which sometimes return correct, and sometimes incorrect JSON-RPC 2.0 responses - sounds really crazy!

**Comment by antness** [comment] 2018-02-21 13:33
Actually I don't know what exactly was the reason of failure when it was in production. Here I just demonstrated that problem exists and there is a quick way to reproduce it.

Anyway, there is still no reason to break all subsequent calls even if there was JSON-RPC level error.

**Comment by antness** [comment] 2018-02-21 14:20
> Protocol level errors usually mean this server isn't compatible with JSON-RPC 2.0, which is fatal error and there is no sense in continue sending requests to this server - so Client shutdown in this case.

I agree, but as I mentioned above, server side handlers are implemented by 3rd parties and there could happen anything anytime. We can't assume these handlers to be 100% compatible with JSON-RPC 2.0 especially while in development stage.

**Comment by powerman** [comment] 2018-02-21 16:40
The point isn't in trust remote side to send only valid data - it's about reasoning to **continue talking** to remote which doesn't implement protocol correctly. I believe it doesn't makes any sense. If service and client implement protocol differently then one of them should be modified to match protocol used by the other side.

Okay, we can "fix" Client to ignore responses with `"jsonrpc":"3.0"` without shutting client down. What's next? How far we should go down this path? A service may **sometimes** return result in `"results":…` instead of `"result":…` and we'll want to handle such responses instead of ignoring them, so???

To me all of this sounds pretty simple: if you've 3rd-party service which doesn't conform to JSON-RPC 2.0 protocol, and you can't do anything to fix this service, then probably you need similarly incompatible client working in same way as a service - i.e. create own client for JSON-RPC-like protocol used by this service instead of trying to use client for JSON-RPC 2.0 protocol which is able to work "most of time" by ignoring random responses which doesn't match the protocol.

All of this is unlikely sounds helpful for you. :disappointed:
But there should be some limit on how far we can go - attempt to handle and survive anything remote 3rd-party buggy development-mode service out of our control may send - is usually very bad idea. Browsers did this in the 90s, and while it probably helps growing web fast, it also makes a lot of harm and web still isn't recovered after this bad decision.

**Comment by antness** [comment] 2018-02-21 17:57
> it's about reasoning to **continue talking** to remote which doesn't implement protocol correctly

Remote is not frozen in time, it could be changed/fixed/broken/fixed again.

> then one of them should be modified to match protocol used by the other side.

Exactly. And when remote handler got fixed everything should work, but now it doesn't. At least without rpc.Client recreation.

> Okay, we can "fix" Client to ignore responses with "jsonrpc":"3.0" without shutting client down.

We can treat every request/response separately from the others. Every call is independent and do not break the whole client, just like you handle transport-level errors. From my point of view JSON-RPC 2.0 is transport level for my data and I want it to work and not to find reasons to break.

In my opinion, library should do as mush as possible to handle every single call and forgive non-fatal errors. For example, requirement for "Accept" header to exactly match string "application/json" is too much restrictive and it violates HTTP protocol by itself (`application/json, application/grpc`, `application/*`, `*/*` are valid values for JSON-RPC request and even absence of the header is valid and shouldn't make request fail). Same about "Content-Type" header.

**Comment by antness** [comment] 2018-02-21 18:21
> How far we should go down this path?

I see no sence in breaking subsequent calls after any kind of failure. Decision to stop talking to endpoint is my responsibility as user of the library. Now I don't even have such a choise.

We can fail for specific request and may be give to the user of the library an option to turn off strict mode.

**Comment by powerman** [comment] 2018-02-21 18:53
> For example, requirement for "Accept" header to exactly match string "application/json" is too much restrictive and it violates HTTP protocol by itself

I agree, but this wasn't my decision - it was dictated by the spec, and my decision is to follow a spec as much as possible because there are usually no good reasons to violate a spec.

> I see no sence in breaking subsequent calls after any kind of failure (this concerns any HTTP-based protocol). Decision to stop talking to particular endpoint is my responsibility as user of the library.

Actually I tend to agree. While I still believe it doesn't make sense to continue talking to incompatible endpoint, in case of independent requests this should be user's responsibility and decision, not library's.

**Comment by antness** [comment] 2018-02-21 21:43
Have found a way to reproduce client shutdown issue with HTTP transport level error:
https://gist.github.com/antness/8e3ddaabee0b8c8ea4736af84783000d
Server closes connection in the middle of HTTP-body.
I'm still not sure that it was exactly our case, but it doesn't matter. I believe that stateless protocols shouldn't maintain any state.

**Comment by Scukerman** [comment] 2018-03-01 07:10
@powerman 
Memory is not leaking anymore. Thx.
As for another question, it's up to to close this issue.

**Comment by powerman** [comment] 2018-03-01 08:05
Reopening to track second issue with making transport-level errors non-fatal for HTTP Client.

**Comment by powerman** [comment] 2018-03-01 10:04
@antness It doesn't looks like it's possible to make current implementation resistant to transport-level errors. Sure, I can make some errors non-fatal, but this won't solve all cases anyway.

Let's forget about HTTP for a moment, and think in terms of single TCP connection. There are two interesting cases:
1. If server is broken then it may respond with incomplete JSON for one of requests. For ex. server may send just one symbol `[` instead of complete response, which will result in freezing all Call() of this Client because decoding response on client side won't complete until EOF, which may never happens if server won't close the connection. Only way to protect against this on client side is to add some timeout and close the connection on client side, which means closing the Client.
2. If server is broken then it may response with complete but wrong JSON. For ex. `"jsonrpc":"3.0"`. Now everything depends on our ability to tie this wrong response to one of pending requests: if we can do this then we can return non-fatal error to this request's Call() and keep Client alive, else we have to signal error to all pending requests, and only way to do this in `net/rpc` codec is to return EOF and thus close Client. (In general it means we must get at least `{"jsonrpc":"2.0","id":ID}` to be able to use given ID.)

For HTTP clients current architecture simulate single byte stream (like TCP connection) per Client. This means it join HTTP responses, so both TCP issues currently apply to HTTP as well. This is probably not a good thing, because with HTTP there is a higher chance to get into case 1 because of receiving part of HTTP body (i.e. incomplete JSON). This can be worked around by checking is HTTP response contains complete JSON before joining it with other responses - but this will add slowdown because of extra JSON decoding. As for case 2, with HTTP we're able to decode request ID from POST body before sending it, and thus we can generate own "fake" error response for this ID in case server won't send correct response - but this extra JSON decoding of request will add more slowdown.

I'm not sure is it worth it. While it looks like we can make HTTP client resistant to bad responses it'll require two extra JSON decoding and it'll make HTTP client's behaviour differ from TCP client's behaviour (users will have to handle Shutdown/UnexpectedEOF only for TCP Clients).

So, I think needs to handle Shutdown/UnexpectedEOF and re-create Client in case of these errors is part of `net/rpc` interface and we shouldn't try to fight against it. While it may be inconvenient and not necessary in case of JSON-RPC 2.0 over HTTP, probably best way to solve it is to implement this protocol in separate package, independent from `net/rpc`. I suppose `net/rpc` doc says "The net/rpc package is frozen and is not accepting new features." just because of it current limitations, which makes it not so good as a base for implementing other protocols as `net/rpc` codecs.

If you disagree - please open new issue to continue.

**Closed by powerman** 2018-03-01 10:04 UTC
